CREATE TABLE [interhome].[imp_property](
	[place_Id] [bigint] NOT NULL,
	[runId] [int] NOT NULL,
	[fileId] [int] NOT NULL,
	[sourceId] [int] NOT NULL,
	[loopNo] [int] NULL,
	[name] [nvarchar](255) NULL,
	[externalId] [nvarchar](100) NULL,
	[externalURL] [nvarchar](2000) NULL,
	[thumbnailURL] [nvarchar](2000) NULL,
	[description] [nvarchar](4000) NULL,
	[typeOfProperty] [nvarchar](255) NULL,
	[postcode] [nvarchar](255) NULL,
	[cityName] [nvarchar](255) NULL,
	[stateName] [nvarchar](255) NULL,
	[country] [nvarchar](255) NULL,
	[countryCode] [nvarchar](10) NULL,
	[latitude] [decimal](28, 10) NULL,
	[longitude] [decimal](28, 10) NULL,
	[minimumPricePerNight] [decimal](10, 2) NULL,
	[propertyCurrencyCode] [nvarchar](10) NULL,
	[numberOfProperBedrooms] [int] NULL,
	[numberOfBathrooms] [int] NULL,
	[maximumNumberOfPeople] [int] NULL,
	[minimumDaysOfStay] [int] NULL
) ON [PRIMARY]
