CREATE TABLE [housetrip].[imp_property] (
    [sourceId]                                     INT             NOT NULL,
    [runId]                                        INT             NOT NULL,
    [fileId]                                       INT             NOT NULL,
    [imp_propertiesId]                             INT             NOT NULL,
    [id]                                           INT             NOT NULL,
    [landing_page_url]                             NVARCHAR (255)  NULL,
    [description]                                  NVARCHAR (4000) NULL,
    [name]                                         NVARCHAR (255)  NULL,
    [region_name]                                  NVARCHAR (255)  NULL,
    [type_of_property]                             NVARCHAR (50)   NULL,
    [zip_code]                                     NVARCHAR (255)  NULL,
    [region_id]                                    INT             NULL,
    [city_id]                                      INT             NULL,
    [city_name]                                    NVARCHAR (255)  NULL,
    [country_code]                                 NVARCHAR (2)    NULL,
    [latitude]                                     FLOAT (53)      NULL,
    [longitude]                                    FLOAT (53)      NULL,
    [check_in_from]                                TIME (7)        NULL,
    [check_out_before]                             TIME (7)        NULL,
    [size_of_space_in_sqm]                         INT             NULL,
    [size_of_space_in_sqft]                        INT             NULL,
    [cancellation_policy]                          NVARCHAR (255)  NULL,
    [minimum_price_per_night]                      INT             NULL,
    [currency_code]                                NVARCHAR (3)    NULL,
    [number_of_proper_bedrooms]                    INT             NULL,
    [number_of_bathrooms]                          INT             NULL,
    [floor]                                        INT             NULL,
    [reviews_count]                                INT             NULL,
    [average_rating]                               FLOAT (53)      NULL,
    [maximum_number_of_people]                     INT             NULL,
    [number_of_other_rooms_where_guests_can_sleep] INT             NULL,
    [kitchen]                                      BIT             NULL,
    [non_smoking_only]                             BIT             NULL,
    [wheelchair_accessible]                        BIT             NULL,
    [pets_not_allowed]                             BIT             NULL,
    [children_friendly]                            BIT             NULL,
    [entire_property]                              BIT             NULL,
    [elevator]                                     BIT             NULL,
    [minimum_length_of_stay]                       BIT             NULL,
    [minimum_days_of_stay]                         INT             NULL,
    CONSTRAINT [PK_housetrip_property] PRIMARY KEY CLUSTERED ([runId] ASC, [id] ASC)
);

