CREATE TABLE [flipkey].[imp_property] (
    [property_Id]                     BIGINT           NULL,
    [detailsCheck_in]                 NVARCHAR (255)   NULL,
    [detailsCheck_out]                NVARCHAR (255)   NULL,
    [detailsName]                     NVARCHAR (255)   NULL,
    [detailsElder]                    NVARCHAR (10)    NULL,
    [detailsBathroom_count]           DECIMAL (10, 2)  NULL,
    [detailsBedroom_count]            INT              NULL,
    [detailsPet]                      NVARCHAR (10)    NULL,
    [detailsUnit_size]                NVARCHAR (255)   NULL,
    [detailsCurrency]                 NVARCHAR (255)   NULL,
    [detailsHandicap]                 NVARCHAR (10)    NULL,
    [detailsMinimum_stay]             INT              NULL,
    [detailsOccupancy]                INT              NULL,
    [detailsSmoking]                  NVARCHAR (10)    NULL,
    [detailsUrl]                      NVARCHAR (2000)  NULL,
    [detailsUnit_size_units]          NVARCHAR (20)    NULL,
    [detailsProperty_type]            NVARCHAR (20)    NULL,
    [detailsChildren]                 NVARCHAR (255)   NULL,
    [propertyDescription]             NVARCHAR (4000)  NULL,
    [review_count]                    INT              NULL,
    [flagsCalendar_export_url]        NVARCHAR (2000)  NULL,
    [flagsRates_updated]              DATETIME         NULL,
    [flagsLast_booked_date]           DATETIME         NULL,
    [flagsHas_special]                BIT              NULL,
    [flagsPhotos_updated]             DATETIME         NULL,
    [flagsIs_tip]                     NVARCHAR (255)   NULL,
    [flagsCalendar_updated]           DATETIME         NULL,
    [flagsAlt_photo_test]             NVARCHAR (255)   NULL,
    [flagsAlt_pdp_sprite_filename_v2] NVARCHAR (255)   NULL,
    [addressCity]                     NVARCHAR (255)   NULL,
    [addressLocation_name]            NVARCHAR (255)   NULL,
    [addressZip]                      NVARCHAR (255)   NULL,
    [addressAddress1]                 NVARCHAR (255)   NULL,
    [addressAddress2]                 NVARCHAR (255)   NULL,
    [addressPrecision]                NVARCHAR (10)    NULL,
    [addressLongitude]                FLOAT (53)       NULL,
    [addressShow_exact_address]       INT              NULL,
    [addressState]                    NVARCHAR (255)   NULL,
    [addressNew_location_id]          INT              NULL,
    [addressCountry]                  NVARCHAR (255)   NULL,
    [addressLatitude]                 FLOAT (53)       NULL,
    [review_sum]                      INT              NULL,
    [review_photos]                   INT              NULL,
    [rateUser_day_min_rate]           DECIMAL (10, 2)  NULL,
    [rateDay_max_rate]                DECIMAL (10, 2)  NULL,
    [rateUser_week_min_rate]          DECIMAL (10, 2)  NULL,
    [rateUser_month_max_rate]         DECIMAL (10, 2)  NULL,
    [rateWeek_max_rate]               DECIMAL (10, 2)  NULL,
    [rateUser_week_max_rate]          DECIMAL (10, 2)  NULL,
    [rateUser_month_min_rate]         DECIMAL (10, 2)  NULL,
    [rateMonth_max_rate]              DECIMAL (10, 2)  NULL,
    [rateMinimum_length]              INT              NULL,
    [rateMonth_min_rate]              DECIMAL (10, 2)  NULL,
    [rateUser_day_max_rate]           DECIMAL (10, 2)  NULL,
    [rateDay_min_rate]                DECIMAL (10, 2)  NULL,
    [rateWeek_min_rate]               DECIMAL (10, 2)  NULL,
    [attributesUser_id]               INT              NULL,
    [attributesIs_revgen]             NVARCHAR (255)   NULL,
    [attributesModified]              DATETIME         NULL,
    [attributesService_level_id]      INT              NULL,
    [attributesDirect]                NVARCHAR (255)   NULL,
    [attributesScore]                 DECIMAL (28, 10) NULL,
    [attributesUser_group_id]         INT              NULL,
    [attributesFrontdesk_id]          INT              NULL,
    [attributesProperty_id]           INT              NULL,
    [specialAmt_off_per_night]        DECIMAL (10, 2)  NULL,
    [specialAmt_off_per_stay]         DECIMAL (10, 2)  NULL,
    [specialCurrency]                 NVARCHAR (255)   NULL,
    [specialDescription]              NVARCHAR (4000)  NULL,
    [specialTitle]                    NVARCHAR (255)   NULL,
    [specialFree_stuff_title]         NVARCHAR (255)   NULL,
    [specialNum_free_nights]          NVARCHAR (255)   NULL,
    [specialOut_of_num_nights]        INT              NULL,
    [specialPct_off_rate]             DECIMAL (10, 2)  NULL,
    [specialPublish_start_date]       DATETIME         NULL,
    [specialPublish_end_date]         DATETIME         NULL,
    [specialRental_start_date]        DATETIME         NULL,
    [specialRental_end_date]          DATETIME         NULL,
    [specialSpecial_type_description] NVARCHAR (50)    NULL,
    [runId]                           INT              NOT NULL,
    [fileId]                          INT              NOT NULL,
    [sourceId]                        INT              NOT NULL, 
    [externalId] NVARCHAR(100) NULL
);





