CREATE TABLE [flipkey].[imp_property] (
    [sourceId]                     INT             NOT NULL,
    [runId]                        INT             NOT NULL,
    [fileId]                       INT             NOT NULL,
    [property_Id]                  BIGINT          NULL,
    [city]                         NVARCHAR (255)  NULL,
    [zip]                          NVARCHAR (255)  NULL,
    [address1]                     NVARCHAR (255)  NULL,
    [address2]                     NVARCHAR (255)  NULL,
    [longitude]                    DECIMAL (10, 2) NULL,
    [precision]                    NVARCHAR (255)  NULL,
    [show_exact_address]           DECIMAL (10, 2) NULL,
    [state]                        NVARCHAR (255)  NULL,
    [subregion]                    NVARCHAR (255)  NULL,
    [country]                      NVARCHAR (255)  NULL,
    [latitude]                     DECIMAL (10, 2) NULL,
    [review_count]                 DECIMAL (10, 2) NULL,
    [review_photos]                DECIMAL (10, 2) NULL,
    [review_sum]                   DECIMAL (10, 2) NULL,
    [check_in]                     NVARCHAR (255)  NULL,
    [check_out]                    NVARCHAR (255)  NULL,
    [name]                         NVARCHAR (255)  NULL,
    [bathroom_count]               DECIMAL (10, 2) NULL,
    [bedroom_count]                DECIMAL (10, 2) NULL,
    [currency]                     NVARCHAR (255)  NULL,
    [elder]                        NVARCHAR (255)  NULL,
    [handicap]                     NVARCHAR (255)  NULL,
    [minimum_stay]                 DECIMAL (10, 2) NULL,
    [occupancy]                    DECIMAL (10, 2) NULL,
    [pet]                          NVARCHAR (255)  NULL,
    [smoking]                      NVARCHAR (255)  NULL,
    [unit_size]                    NVARCHAR (255)  NULL,
    [url]                          NVARCHAR (2000) NULL,
    [unit_size_units]              NVARCHAR (255)  NULL,
    [property_type]                NVARCHAR (255)  NULL,
    [children]                     NVARCHAR (255)  NULL,
    [user_id]                      DECIMAL (10, 2) NULL,
    [modified]                     DATETIME        NULL,
    [score]                        NVARCHAR (255)  NULL,
    [user_group_id]                DECIMAL (10, 2) NULL,
    [frontdesk_id]                 DECIMAL (10, 2) NULL,
    [rates_updated]                DATETIME        NULL,
    [last_booked_date]             DATETIME        NULL,
    [has_special]                  DECIMAL (10, 2) NULL,
    [photos_updated]               DATETIME        NULL,
    [calendar_updated]             DATETIME        NULL,
    [day_max_rate]                 DECIMAL (10, 2) NULL,
    [day_min_rate]                 DECIMAL (10, 2) NULL,
    [minimum_length]               DECIMAL (10, 2) NULL,
    [month_max_rate]               DECIMAL (10, 2) NULL,
    [month_min_rate]               DECIMAL (10, 2) NULL,
    [week_max_rate]                NVARCHAR (255)  NULL,
    [week_min_rate]                DECIMAL (10, 2) NULL,
    [user_day_max_rate]            DECIMAL (10, 2) NULL,
    [user_day_min_rate]            DECIMAL (10, 2) NULL,
    [user_month_max_rate]          DECIMAL (10, 2) NULL,
    [user_month_min_rate]          DECIMAL (10, 2) NULL,
    [user_week_max_rate]           NVARCHAR (255)  NULL,
    [user_week_min_rate]           NVARCHAR (255)  NULL,
    [amt_off_per_night]            DECIMAL (10, 2) NULL,
    [amt_off_per_stay]             DECIMAL (10, 2) NULL,
    [property_special_currency]    NVARCHAR (255)  NULL,
    [property_special_description] NVARCHAR (4000) NULL,
    [title]                        NVARCHAR (255)  NULL,
    [free_stuff_title]             NVARCHAR (255)  NULL,
    [num_free_nights]              NVARCHAR (255)  NULL,
    [out_of_num_nights]            DECIMAL (10, 2) NULL,
    [pct_off_rate]                 DECIMAL (10, 2) NULL,
    [publish_start_date]           DATETIME        NULL,
    [publish_end_date]             DATETIME        NULL,
    [rental_start_date]            DATETIME        NULL,
    [rental_end_date]              DATETIME        NULL,
    [special_type_description]     NVARCHAR (4000) NULL,
    [propertyType]                 NVARCHAR (255)  NULL,
    [propertyDescription]          NVARCHAR (4000) NULL
);

