CREATE TABLE [roomorama].[imp_property] (
    [room_Id]                 INT			   NULL,
    [id]                      INT			   NULL,
    [title]                   NVARCHAR (255)   NULL,
    [type]                    NVARCHAR (255)   NULL,
    [subtype]                 NVARCHAR (255)   NULL,
    [url]                     NVARCHAR (2000)  NULL,
    [num-rooms]               DECIMAL (28, 10) NULL,
    [num-bathrooms]           DECIMAL (28, 10) NULL,
    [max-guests]              DECIMAL (28, 10) NULL,
    [min-stay]                DECIMAL (28, 10) NULL,
    [floor]                   NVARCHAR (50)    NULL,
    [num-double-beds]         DECIMAL (28, 10) NULL,
    [num-single-beds]         DECIMAL (28, 10) NULL,
    [num-sofa-beds]           DECIMAL (28, 10) NULL,
    [surface]                 DECIMAL (28, 10) NULL,
    [price]                   DECIMAL (28, 10) NULL,
    [tax-rate]                DECIMAL (28, 10) NULL,
    [extra-charges]           DECIMAL (28, 10) NULL,
    [currency-code]           NVARCHAR (255)   NULL,
    [currency-display]        NVARCHAR (255)   NULL,
    [description]             NVARCHAR (4000)  NULL,
    [city]                    NVARCHAR (255)   NULL,
    [country-code]            NVARCHAR (255)   NULL,
    [lat]                     DECIMAL (28, 10) NULL,
    [lng]                     DECIMAL (28, 10) NULL,
    [amenities]               NVARCHAR (2000)  NULL,
    [smoking]                 BIT              NULL,
    [pets]                    BIT              NULL,
    [children]                BIT              NULL,
    [cleaningAvailable]       BIT              NULL,
    [cleaningRate]            NVARCHAR (255)    NULL,
    [cleaningRequired]        BIT              NULL,
    [airport-pickupAvailable] BIT              NULL,
    [airport-pickupRate]      NVARCHAR (255)    NULL,
    [car-rentalAvailable]     BIT              NULL,
    [car-rentalRate]          NVARCHAR (255)    NULL,
    [conciergeAvailable]       BIT              NULL,
    [conciergeRate]           NVARCHAR (255)    NULL,
    [check-in-time]           NVARCHAR (255)   NULL,
    [check-out-time]          NVARCHAR (255)   NULL,
    [check-in-instructions]   NVARCHAR (4000)  NULL,
    [cancellation-policy]     NVARCHAR (4000)   NULL,
    [multi-unit]              BIT              NULL,
    [instantly-bookable]      BIT              NULL,
    [created-at]              NVARCHAR (20)    NULL,
    [updated-at]              NVARCHAR (20)    NULL,
    [calendar-updated-at]     NVARCHAR (20)    NULL,
    [security-deposit]        NVARCHAR (4000)  NULL,
    [units]                   NVARCHAR (4000)  NULL,
    [hostId]                  INT			   NULL,
    [hostDisplay]             NVARCHAR (255)   NULL,
    [hostCertified]           BIT              NULL,
    [hostUrl]                 NVARCHAR (2000)  NULL,
    [runId]                   INT              NULL,
    [fileId]                  INT              NULL,
    [sourceId]                INT              NULL, 
    [periodType]			  NVARCHAR(255) NULL
);
GO

CREATE CLUSTERED INDEX [CX_roomorama_imp_property_runId_fileId_id, room_Id]
    ON [roomorama].[imp_property]([runId] ASC, [fileId] ASC, [id] ASC, [room_Id] ASC);
GO

