CREATE TABLE [dbo].[utils_countryLookup] (
    [id]                          INT            IDENTITY (1, 1) NOT NULL,
    [iso2]                        CHAR (2)       NOT NULL,
    [longName]                    NVARCHAR (100) NOT NULL,
    [searchTerm]                  NVARCHAR (100) NOT NULL,
    [centralLatitude]             FLOAT (53)     NULL,
    [centralLongitude]            FLOAT (53)     NULL,
    [swLatitude]                  FLOAT (53)     NULL,
    [swLongitude]                 FLOAT (53)     NULL,
    [neLatitude]                  FLOAT (53)     NULL,
    [neLongitude]                 FLOAT (53)     NULL,
    [radius]                      INT            CONSTRAINT [DF_utils_countryLookup_radius] DEFAULT ((0)) NOT NULL,
    [createdDate]                 DATETIME       CONSTRAINT [DF_utils_countryLookup_createdDate] DEFAULT (getdate()) NOT NULL,
    [street_address]              NVARCHAR (500) NULL,
    [route]                       NVARCHAR (500) NULL,
    [intersection]                NVARCHAR (500) NULL,
    [political]                   NVARCHAR (500) NULL,
    [country]                     NVARCHAR (500) NULL,
    [administrative_area_level_1] NVARCHAR (500) NULL,
    [administrative_area_level_2] NVARCHAR (500) NULL,
    [administrative_area_level_3] NVARCHAR (500) NULL,
    [administrative_area_level_4] NVARCHAR (500) NULL,
    [administrative_area_level_5] NVARCHAR (500) NULL,
    [colloquial_area]             NVARCHAR (500) NULL,
    [locality]                    NVARCHAR (500) NULL,
    [ward]                        NVARCHAR (500) NULL,
    [sublocality]                 NVARCHAR (500) NULL,
    [sublocality_level_1]         NVARCHAR (500) NULL,
    [sublocality_level_2]         NVARCHAR (500) NULL,
    [sublocality_level_3]         NVARCHAR (500) NULL,
    [sublocality_level_4]         NVARCHAR (500) NULL,
    [sublocality_level_5]         NVARCHAR (500) NULL,
    [neighborhood]                NVARCHAR (500) NULL,
    [premise]                     NVARCHAR (500) NULL,
    [subpremise]                  NVARCHAR (500) NULL,
    [postal_code]                 NVARCHAR (500) NULL,
    [natural_feature]             NVARCHAR (500) NULL,
    [airport]                     NVARCHAR (500) NULL,
    [park]                        NVARCHAR (500) NULL,
    [point_of_interest]           NVARCHAR (500) NULL,
    [postal_town]                 NVARCHAR (500) NULL,
    CONSTRAINT [PK_utils_countryLookup] PRIMARY KEY CLUSTERED ([id] ASC)
);





